version: '2.2'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial 
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true 
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true 
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ports:
      - 9200:9200
    networks:
      - elastic

    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kib01:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    container_name: kib01
    # depends_on: {"es01": {"condition": "service_healthy"}}
    ports:
      - 5601:5601
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: https://es01:9200
      ELASTICSEARCH_HOSTS: https://es01:9200
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: UvHzL6gbntHqObzLC72Y
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: $CERTS_DIR/ca/ca.crt
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: $CERTS_DIR/kib01/kib01.key
      SERVER_SSL_CERTIFICATE: $CERTS_DIR/kib01/kib01.crt
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "any_thing_of_32_character_long_valid"
      XPACK_ACTTIONS_WHITELISTEDHOSTS: "['*']"
      XPACK.ACTTIONS.ENABLEACTIONTYPES: "['*']"
      # xpack.encryptedSavedObjects.encryptionKey
      # xpack.actions.whitelistedHosts
      # xpack.actions.enabledActionTypes




    volumes:
      - certs:$CERTS_DIR
    networks:
      - elastic

  filebeat01:
    image: docker.elastic.co/beats/filebeat:${VERSION}
    container_name: filebeat01
    depends_on: 
      - "es01"
    ports:
      - 5044:5044
    # environment:
    #   # SERVERNAME: localhost
    #   # ELASTICSEARCH_URL: https://es01:9200
    #   ELASTICSEARCH_HOSTS: https://es01:9200
    #   ELASTICSEARCH_USERNAME: elastic
    #   ELASTICSEARCH_PASSWORD: GHimwcXsFGNDVCDG81SO
    #   ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: $CERTS_DIR/ca/ca.crt
    #   SERVER_SSL_ENABLED: "true"
      # SERVER_SSL_KEY: $CERTS_DIR/kib01/kib01.key
      # SERVER_SSL_CERTIFICATE: $CERTS_DIR/kib01/kib01.crt
    volumes:
      - certs:$CERTS_DIR
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./sample-log/logstash-sample.log:/usr/share/filebeat/logstash-sample.log
    networks:
      - elastic

volumes:
  data01:
    driver: local
  certs:
    driver: local

networks:
  elastic:
    driver: bridge